name: Build qaac portable and singleton

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Install tools
      run: choco install -y 7zip innoextract

    - name: Get latest Enigma Virtual Box release
      run: |
        curl -s https://api.github.com/repos/dirkarnez/enigma-virtual-box-portable/releases/latest \
        | grep "browser_download_url" \
        | grep "enigma-virtual-box-portable-v.*\.zip" \
        | cut -d '"' -f 4 \
        | xargs curl -L -o enigmavb.zip

    - name: Extract Enigma Virtual Box
      run: 7z x enigmavb.zip -oenigmavb

    - name: Download latest qaac release
      run: |
        QAAC_URL=$(curl -s https://api.github.com/repos/nu774/qaac/releases/latest \
          | grep "browser_download_url" \
          | grep "qaac_.*\.zip" \
          | cut -d '"' -f 4)
        QAAC_VERSION=$(basename "$QAAC_URL" | sed 's/qaac_\(.*\)\.zip/\1/')
        echo "QAAC_VERSION=$QAAC_VERSION" >> $GITHUB_ENV
        curl -L -o qaac.zip "$QAAC_URL"

    - name: Extract qaac and prepare folders
      run: |
        7z x qaac.zip
        mkdir -p win32 win64
        cp qaac_*/x86/* win32/
        cp qaac_*/x64/* win64/

    - name: Download iTunes installers
      run: |
        curl -L -o iTunes32.exe "https://www.apple.com/itunes/download/win32"
        curl -L -o iTunes64.exe "https://www.apple.com/itunes/download/win64"

    - name: Extract DLLs
      run: |
        mkdir -p itunes32 itunes64
        innoextract -d itunes32 iTunes32.exe
        innoextract -d itunes64 iTunes64.exe

        DLLS=("ASL.dll" "CoreAudioToolbox.dll" "CoreFoundation.dll" "libdispatch.dll" "libicuin.dll" "libicuuc.dll" "objc.dll")
        for dll in "${DLLS[@]}"; do
          find itunes32 -iname "$dll" -exec cp {} win32/ \;
          find itunes64 -iname "$dll" -exec cp {} win64/ \;
        done

        find itunes32 -iname "icudt*.dll" -exec cp {} win32/ \;
        find itunes64 -iname "icudt*.dll" -exec cp {} win64/ \;

    - name: Generate config32.xml
      run: |
        {
          echo "<VirtualBox>"
          echo "  <InputFile>win32\\qaac.exe</InputFile>"
          echo "  <OutputFile>qaac-singleton-win32-${QAAC_VERSION}.exe</OutputFile>"
          echo "  <Files>"
          for f in win32/*.dll; do
            echo "    <File>${f}</File>"
          done
          echo "  </Files>"
          echo "</VirtualBox>"
        } > config32.xml

    - name: Generate config64.xml
      run: |
        {
          echo "<VirtualBox>"
          echo "  <InputFile>win64\\qaac.exe</InputFile>"
          echo "  <OutputFile>qaac-singleton-win64-${QAAC_VERSION}.exe</OutputFile>"
          echo "  <Files>"
          for f in win64/*.dll; do
            echo "    <File>${f}</File>"
          done
          echo "  </Files>"
          echo "</VirtualBox>"
        } > config64.xml

    - name: Run Enigma Virtual Box
      run: |
        ./enigmavb/EnigmaVB.exe config32.xml
        ./enigmavb/EnigmaVB.exe config64.xml

    - name: Package zip bundles
      run: |
        7z a -mx=9 qaac-win32-${QAAC_VERSION}.zip ./win32/*
        7z a -mx=9 qaac-win64-${QAAC_VERSION}.zip ./win64/*

    - name: Upload win32 zip
      uses: actions/upload-artifact@v4
      with:
        name: qaac-win32-${{ env.QAAC_VERSION }}
        path: qaac-win32-${{ env.QAAC_VERSION }}.zip

    - name: Upload win64 zip
      uses: actions/upload-artifact@v4
      with:
        name: qaac-win64-${{ env.QAAC_VERSION }}
        path: qaac-win64-${{ env.QAAC_VERSION }}.zip

    - name: Upload singleton win32 EXE
      uses: actions/upload-artifact@v4
      with:
        name: qaac-singleton-win32-${{ env.QAAC_VERSION }}
        path: qaac-singleton-win32-${{ env.QAAC_VERSION }}.exe

    - name: Upload singleton win64 EXE
      uses: actions/upload-artifact@v4
      with:
        name: qaac-singleton-win64-${{ env.QAAC_VERSION }}
        path: qaac-singleton-win64-${{ env.QAAC_VERSION }}.exe
