name: Build qaac portable and singleton

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install tools
      run: choco install -y 7zip innoextract python

    - name: Get latest Enigma Virtual Box release
      shell: bash
      run: |
        curl -s https://api.github.com/repos/dirkarnez/enigma-virtual-box-portable/releases/latest \
        | grep "browser_download_url" \
        | grep "enigma-virtual-box-portable-v.*\.zip" \
        | cut -d '"' -f 4 \
        | xargs curl -L -o enigmavb.zip

    - name: Extract Enigma Virtual Box
      run: 7z x enigmavb.zip -oenigmavb

    - name: Download latest qaac release
      run: |
        curl -sL https://api.github.com/repos/nu774/qaac/releases/latest > latest.json
        $url = (Get-Content latest.json | ConvertFrom-Json).assets | Where-Object { $_.name -like "qaac_*.zip" } | Select-Object -First 1 | Select-Object -ExpandProperty browser_download_url
        $version = $url -replace ".*/qaac_(.*)\.zip", '$1'
        echo "QAAC_VERSION=$version" >> $env:GITHUB_ENV
        curl -L -o qaac.zip $url

    - name: Extract qaac
      run: |
        7z x qaac.zip -oqaac
        mkdir win32 win64
        copy qaac\x86\* win32\
        copy qaac\x64\* win64\

    - name: Download iTunes installers
      run: |
        curl -L -o iTunes32.exe https://www.apple.com/itunes/download/win32
        curl -L -o iTunes64.exe https://www.apple.com/itunes/download/win64

    - name: Extract DLLs
      run: |
        mkdir itunes32 itunes64
        innoextract -d itunes32 iTunes32.exe
        innoextract -d itunes64 iTunes64.exe

        for %%d in (
          ASL.dll CoreAudioToolbox.dll CoreFoundation.dll
          libdispatch.dll libicuin.dll libicuuc.dll objc.dll
        ) do (
          for /r itunes32 %%f in (%%d) do copy "%%f" win32\
          for /r itunes64 %%f in (%%d) do copy "%%f" win64\
        )
        for /r itunes32 %%f in (icudt*.dll) do copy "%%f" win32\
        for /r itunes64 %%f in (icudt*.dll) do copy "%%f" win64\

    - name: Generate Enigma config (win32)
      shell: python
      run: |
        import os
        from xml.etree.ElementTree import Element, SubElement, tostring
        from xml.dom.minidom import parseString

        version = os.environ["QAAC_VERSION"]
        files = os.listdir("win32")
        root = Element("VirtualBox")
        SubElement(root, "InputFile").text = f"win32\\qaac.exe"
        SubElement(root, "OutputFile").text = f"qaac-singleton-win32-{version}.exe"
        files_elem = SubElement(root, "Files")
        for f in files:
            if f.lower() != "qaac.exe":
                SubElement(files_elem, "File").text = f"win32\\{f}"
        xml_str = parseString(tostring(root)).toprettyxml(indent="  ")
        with open("config32.xml", "w") as f:
            f.write(xml_str)

    - name: Generate Enigma config (win64)
      shell: python
      run: |
        import os
        from xml.etree.ElementTree import Element, SubElement, tostring
        from xml.dom.minidom import parseString

        version = os.environ["QAAC_VERSION"]
        files = os.listdir("win64")
        root = Element("VirtualBox")
        SubElement(root, "InputFile").text = f"win64\\qaac.exe"
        SubElement(root, "OutputFile").text = f"qaac-singleton-win64-{version}.exe"
        files_elem = SubElement(root, "Files")
        for f in files:
            if f.lower() != "qaac.exe":
                SubElement(files_elem, "File").text = f"win64\\{f}"
        xml_str = parseString(tostring(root)).toprettyxml(indent="  ")
        with open("config64.xml", "w") as f:
            f.write(xml_str)

    - name: Run Enigma Virtual Box
      run: |
        enigmavb\EnigmaVB.exe config32.xml
        enigmavb\EnigmaVB.exe config64.xml

    - name: Package zip bundles
      run: |
        7z a -mx=9 qaac-win32-%QAAC_VERSION%.zip .\win32\*
        7z a -mx=9 qaac-win64-%QAAC_VERSION%.zip .\win64\*

    - name: Upload win32 zip
      uses: actions/upload-artifact@v4
      with:
        name: qaac-win32-${{ env.QAAC_VERSION }}
        path: qaac-win32-${{ env.QAAC_VERSION }}.zip

    - name: Upload win64 zip
      uses: actions/upload-artifact@v4
      with:
        name: qaac-win64-${{ env.QAAC_VERSION }}
        path: qaac-win64-${{ env.QAAC_VERSION }}.zip

    - name: Upload singleton win32 EXE
      uses: actions/upload-artifact@v4
      with:
        name: qaac-singleton-win32-${{ env.QAAC_VERSION }}
        path: qaac-singleton-win32-${{ env.QAAC_VERSION }}.exe

    - name: Upload singleton win64 EXE
      uses: actions/upload-artifact@v4
      with:
        name: qaac-singleton-win64-${{ env.QAAC_VERSION }}
        path: qaac-singleton-win64-${{ env.QAAC_VERSION }}.exe
